services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
      
  postgres:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  bot:
    container_name: dpch
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      RUST_LOG: info
      TELOXIDE_TOKEN: ${TELOXIDE_TOKEN}
      
volumes:
  postgres_data:
